# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-25 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_basicapp_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicapp',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
